const KEY='kp_students';let students=JSON.parse(localStorage.getItem(KEY)||'[]'),current='home';
const money=n=>new Intl.NumberFormat('uz-UZ').format(n).replaceAll(',',' ')+' so\'m';
const month=()=>{let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')};
const monthName=()=>new Intl.DateTimeFormat('uz-UZ',{month:'long',year:'numeric'}).format(new Date());
const due=()=>new Date().getDate()<=20?250000:280000;
const paid=s=>(s.payments||[]).some(p=>p.month===month());
const save=()=>localStorage.setItem(KEY,JSON.stringify(students));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>esc(n.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase());
document.getElementById('month').textContent=monthName();
function page(p){current=p;render()}
function render(){let x=document.getElementById('app');if(current==='home')x.innerHTML=home();if(current==='students')x.innerHTML=students();if(current==='payments')x.innerHTML=payments();if(current==='settings')x.innerHTML=settings()}
function stat(a,b,c){return `<div class="card"><div class="label">${a}</div><div class="value ${c}">${b}</div></div>`}
function home(){let ok=students.filter(paid).length, debt=students.length-ok;let inc=students.flatMap(s=>s.payments||[]).filter(p=>p.month===month()).reduce((a,p)=>a+p.amount,0);return `<div class="grid">${stat('O‘quvchilar',students.length,'blue')}${stat('To‘laganlar',ok,'green')}${stat('Qarzdorlar',debt,'red')}${stat('Tushum',money(inc),'blue')}</div><div class="box"><div class="label">Bugungi tarif</div><div class="value">${money(due())}</div><div class="small">${new Date().getDate()<=20?'20-sanagacha':'21-sanadan boshlab'}</div></div><div class="title">Tezkor amal</div><button class="btn" onclick="addStudent()">＋ O‘quvchi qo‘shish</button><div class="title">Qarzdorlar</div><div class="box">${students.filter(s=>!paid(s)).slice(0,8).map(row).join('')||'<div class="empty">Qarzdorlar yo‘q 🎉</div>'}</div>`}
function row(s){return `<div class="row" onclick="profile('${s.id}')"><div class="avatar">${initials(s.name)}</div><div class="grow"><div class="name">${esc(s.name)}</div><div class="small">${esc(s.group||'Guruh kiritilmagan')}</div></div><span class="badge ${paid(s)?'paid':'debt'}">${paid(s)?'To‘langan':money(due())}</span></div>`}
function students(){return `<input class="search" placeholder="O‘quvchi yoki guruh qidirish..." oninput="filterStudents(this.value)"><button class="btn secondary" onclick="addStudent()">＋ Yangi o‘quvchi</button><div class="box" id="list">${students.map(row).join('')||'<div class="empty">Hozircha o‘quvchilar yo‘q</div>'}</div>`}
function filterStudents(q){let a=students.filter(s=>(s.name+' '+s.group).toLowerCase().includes(q.toLowerCase()));document.getElementById('list').innerHTML=a.map(row).join('')||'<div class="empty">Topilmadi</div>'}
function payments(){let ok=students.filter(paid);let inc=ok.flatMap(s=>s.payments||[]).filter(p=>p.month===month()).reduce((a,p)=>a+p.amount,0);return `<div class="box"><div class="label">${monthName()} tushumi</div><div class="money">${money(inc)}</div><div class="small">${ok.length} ta o‘quvchi</div></div><div class="title">To‘lov qilganlar</div><div class="box">${ok.map(row).join('')||'<div class="empty">To‘lovlar yo‘q</div>'}</div>`}
function settings(){return `<div class="title">To‘lov qoidasi</div><div class="box"><div class="row"><div class="grow">1–20-sana</div><b>250 000 so‘m</b></div><div class="row"><div class="grow">21-sanadan</div><b>280 000 so‘m</b></div></div><div class="title">Ma'lumotlar</div><button class="btn danger" onclick="wipe()">Barcha ma'lumotlarni o‘chirish</button>`}
function modal(html){let m=document.createElement('div');m.className='modal';m.id='modal';m.innerHTML=`<div class="sheet">${html}</div>`;document.body.appendChild(m)}
function close(){document.getElementById('modal')?.remove()}
function addStudent(){modal(`<h2>Yangi o‘quvchi</h2><input id="n" placeholder="Ism-familiya *"><input id="ph" placeholder="O‘quvchi telefoni" type="tel"><input id="pn" placeholder="Ota-ona ismi"><input id="pp" placeholder="Ota-ona telefoni" type="tel"><input id="g" placeholder="Guruh"><div class="actions"><button class="btn close" onclick="close()">Bekor</button><button class="btn" onclick="saveStudent()">Saqlash</button></div>`)}
function saveStudent(){let n=document.getElementById('n').value.trim();if(!n)return alert('Ism-familiyani kiriting');students.push({id:crypto.randomUUID(),name:n,phone:ph.value,parent:pn.value,parentPhone:pp.value,group:g.value,payments:[]});save();close();render()}
function profile(id){let s=students.find(x=>x.id===id);let hist=(s.payments||[]).slice().reverse().map(p=>`<div class="row"><div class="grow"><b>${p.month}</b><div class="small">${esc(p.method)}</div></div><b>${money(p.amount)}</b></div>`).join('');modal(`<h2>${esc(s.name)}</h2><div class="box">📞 ${esc(s.phone||'Kiritilmagan')}<br><br>👨‍👩‍👦 ${esc(s.parent||'Kiritilmagan')}<br><br>📞 ${esc(s.parentPhone||'Kiritilmagan')}<br><br>👥 ${esc(s.group||'Kiritilmagan')}</div><div class="box"><div class="${paid(s)?'green':'red'}"><b>${paid(s)?'✓ To‘langan':'Qarzdor'}</b></div>${!paid(s)?`<div class="money">${money(due())}</div><button class="btn" onclick="payment('${s.id}')">💳 To‘lov qabul qilish</button>`:''}</div><div class="title">To‘lov tarixi</div><div class="box">${hist||'<div class="empty">Tarix yo‘q</div>'}</div><button class="btn close" onclick="close()">Yopish</button>`)}
function payment(id){let s=students.find(x=>x.id===id);modal(`<h2>To‘lov qabul qilish</h2><div class="box"><b>${esc(s.name)}</b><div class="money">${money(due())}</div><div class="small">${monthName()}</div></div><select id="method"><option>Naqd</option><option>Click</option><option>Payme</option><option>Bank</option><option>Boshqa</option></select><div class="actions"><button class="btn close" onclick="close()">Bekor</button><button class="btn" onclick="pay('${id}')">Tasdiqlash</button></div>`)}
function pay(id){let s=students.find(x=>x.id===id);s.payments.push({id:crypto.randomUUID(),month:month(),amount:due(),method:method.value,date:new Date().toISOString()});save();close();render()}
function wipe(){if(confirm('Barcha ma’lumotlar o‘chadi. Davom etilsinmi?')){students=[];save();render()}}
render();